Frontend (#10)
* Initial capacitor shell

Steps:
- `npm init @capacitor/app`
- `npm install`
- `npm start` to test the shell

Note: this doesn't use react yet

* Update the README

* Delete unused files

* Replace index.html with a more basic template

Steps:
- typing html:5 autocompleted to this template

* Add a simple typescript script to log "Hello World"

* Install React
```
npm install react react-dom
npm i -D @types/react @types/react-dom
```

* Write a simple react app

* Update index.html

* Move hello world to App.tsx

* Install @mantine/core

* Use mantine themes

* Install react-router-dom

* Add routers for different urls

* Generate OpenAPI schema

* Generate the openapi typescript client

* Add CORS middleware to the backend api

* clean code in the backend

* Finish Jobs Frontend

* Clean Code

- delete old jobs-api-client npm install
- fix import order
- lint
- fix typescript css imports
```
Cannot find module './AppLayout.module.css' or its corresponding type declarations.ts(2307)
```

---------

Co-authored-by: Helina <helina.berhane@outlook.com>